// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:141729162562:web:6fc5bab7d4e03dea4114db',
    messagingSenderId: '141729162562',
    projectId: 'hotelio-5cd49',
    authDomain: 'hotelio-5cd49.firebaseapp.com',
    storageBucket: 'hotelio-5cd49.appspot.com',
    measurementId: 'G-J2NM4T3GM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:141729162562:android:95893777d6b8d86e4114db',
    messagingSenderId: '141729162562',
    projectId: 'hotelio-5cd49',
    storageBucket: 'hotelio-5cd49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVmsavZ9q3FJuIkUbXuff_FtvAMm0XktE',
    appId: '1:141729162562:ios:d4c693e08e499b564114db',
    messagingSenderId: '141729162562',
    projectId: 'hotelio-5cd49',
    storageBucket: 'hotelio-5cd49.appspot.com',
    iosBundleId: 'com.drexapp.hotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVmsavZ9q3FJuIkUbXuff_FtvAMm0XktE',
    appId: '1:141729162562:ios:488380d66ed6ec614114db',
    messagingSenderId: '141729162562',
    projectId: 'hotelio-5cd49',
    storageBucket: 'hotelio-5cd49.appspot.com',
    iosBundleId: 'com.example.hotelioapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtldHJ0HWeEJRRBOHc-mfwbR5LBs1DNe4',
    appId: '1:141729162562:web:c6c17e04f7f100344114db',
    messagingSenderId: '141729162562',
    projectId: 'hotelio-5cd49',
    authDomain: 'hotelio-5cd49.firebaseapp.com',
    storageBucket: 'hotelio-5cd49.appspot.com',
    measurementId: 'G-5H5BWM1QLH',
  );
}
